#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

# global settings
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_animation_duration    0.0
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.50
yabai -m config window_opacity               on
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config active_window_border_color   0xff3e5ea3
yabai -m config normal_window_border_color   0xff555555
yabai -m config window_border_width          4
yabai -m config window_border_radius         12
yabai -m config window_border_blur           off
yabai -m config window_border_hidpi          on
yabai -m config window_border                off

# Layout & Padding Settings
yabai -m config layout                       bsp
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_balance                 on

yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
yabai -m config right_padding                15
yabai -m config window_gap                   15
yabai -m config external_bar                 all:0:0

# Spaces Settings
yabai -m space 1 --label web
yabai -m space 2 --label code
yabai -m space 3 --label term
yabai -m space 4 --label conf
yabai -m space 5 --label chat
yabai -m space 6 --label cal
yabai -m space 7 --label mail
yabai -m space 8 --label todo
yabai -m space 9 --label music
yabai -m space 10 --label misc

# Mouse Settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# App Exclusions
yabai -m rule --add app="^1Password$"           layer=above manage=off
yabai -m rule --add app="^Activity Monitor$"    layer=above manage=off
yabai -m rule --add app="^App Store$"           layer=above manage=off
yabai -m rule --add app="^Archive Utility$"     layer=above manage=off
yabai -m rule --add app="^Calculator$"          layer=above manage=off
yabai -m rule --add app="^Dictionary$"          layer=above manage=off
yabai -m rule --add app="^Photo Booth$"         layer=above manage=off
yabai -m rule --add app="^Software Update$"     layer=above manage=off
yabai -m rule --add app="^System Preferences$"  layer=above manage=off
yabai -m rule --add app="^VLC$"                 layer=above manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac"  manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)"     manage=off

echo "yabai configuration loaded.."
